r/consensus: specialize fmt::format() for consensus::vote_state
otherwise {fmt} v8 would cause FTBFS like:

ccache /usr/bin/clang++-15 -DFMT_LOCALE -DFMT_SHARED -DSEASTAR_API_LEVEL=6 -DSEASTAR_DEBUG -DSEASTAR_DEBUG_SHARED_PTR -DSEASTAR_DEFAULT_ALLOCATOR -DSEASTAR_SCHEDULING_GROUPS_COUNT=16 -DSEASTAR_SHUFFLE_TASK_QUEUE -DSEASTAR_TYPE_ERASE_MORE -DXXH_PRIVATE_API -DZSTD_STATIC_LINKING_ONLY -I/home/kefu/dev/redpanda/src/v -I/home/kefu/dev/redpanda/build/src/v -isystem /home/kefu/dev/redpanda/build/deps_install/include -isystem /home/kefu/dev/redpanda/build/deps_install/include/hdr -fPIC -fsanitize=undefined -fsanitize=address -fcolor-diagnostics -g -fPIC -Wall -Wextra -Werror -Wno-missing-field-initializers -std=c++20 -U_FORTIFY_SOURCE -DSEASTAR_SSTRING -Werror=unused-result "-Wno-error=#warnings" -fstack-clash-protection -fsanitize=address -fsanitize=undefined -fno-sanitize=vptr -std=c++20 -MD -MT src/v/raft/CMakeFiles/v_raft.dir/consensus.cc.o -MF src/v/raft/CMakeFiles/v_raft.dir/consensus.cc.o.d -o src/v/raft/CMakeFiles/v_raft.dir/consensus.cc.o -c /home/kefu/dev/redpanda/src/v/raft/consensus.cc
In file included from /home/kefu/dev/redpanda/src/v/raft/consensus.cc:10:
In file included from /home/kefu/dev/redpanda/src/v/raft/consensus.h:15:
In file included from /home/kefu/dev/redpanda/src/v/model/fundamental.h:15:
In file included from /home/kefu/dev/redpanda/src/v/ssx/sformat.h:16:
In file included from /usr/include/fmt/format.h:48:
/usr/include/fmt/core.h:1727:3: error: static_assert failed due to requirement 'formattable' "Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt"
  static_assert(
  ^
/usr/include/fmt/core.h:1853:23: note: in instantiation of function template specialization 'fmt::detail::make_arg<true, fmt::basic_format_context<fmt::appender, char>, fmt::detail::type::custom_type, raft::consensus::vote_state &, 0>' requested here
        data_{detail::make_arg<
                      ^
/usr/include/fmt/core.h:1872:10: note: in instantiation of function template specialization 'fmt::format_arg_store<fmt::basic_format_context<fmt::appender, char>, detail::base_named_type<long, raft::raft_group_id_type, std::integral_constant<bool, true>>, model::ntp, const char *, int, raft::consensus::vote_state, raft::vnode, detail::base_named_type<long, model::model_raft_term_id_type, std::integral_constant<bool, true>>>::format_arg_store<detail::base_named_type<long, raft::raft_group_id_type, std::integral_constant<bool, true>> &, model::ntp &, const char *&, int &, raft::consensus::vote_state &, raft::vnode &, detail::base_named_type<long, model::model_raft_term_id_type, std::integral_constant<bool, true>> &>' requested here
  return {std::forward<Args>(args)...};
         ^
/usr/include/fmt/core.h:3148:36: note: in instantiation of function template specialization 'fmt::make_format_args<fmt::basic_format_context<fmt::appender, char>, detail::base_named_type<long, raft::raft_group_id_type, std::integral_constant<bool, true>> &, model::ntp &, const char *&, int &, raft::consensus::vote_state &, raft::vnode &, detail::base_named_type<long, model::model_raft_term_id_type, std::integral_constant<bool, true>> &>' requested here
  return vformat_to(out, fmt, fmt::make_format_args(args...));
                                   ^
/home/kefu/dev/redpanda/build/deps_install/include/seastar/util/log.hh:208:33: note: in instantiation of function template specialization 'fmt::format_to<seastar::internal::log_buf::inserter_iterator, detail::base_named_type<long, raft::raft_group_id_type, std::integral_constant<bool, true>> &, model::ntp &, const char *, int, raft::consensus::vote_state &, raft::vnode &, detail::base_named_type<long, model::model_raft_term_id_type, std::integral_constant<bool, true>> &, 0>' requested here
                    return fmt::format_to(it, fmt::runtime(fmt.format), std::forward<Args>(args)...);
                                ^
/home/kefu/dev/redpanda/src/v/raft/logger.h:59:21: note: in instantiation of function template specialization 'seastar::logger::log<detail::base_named_type<long, raft::raft_group_id_type, std::integral_constant<bool, true>> &, model::ntp &, const char *, int, raft::consensus::vote_state &, raft::vnode &, detail::base_named_type<long, model::model_raft_term_id_type, std::integral_constant<bool, true>> &>' requested here
            raftlog.log(
                    ^
/home/kefu/dev/redpanda/src/v/raft/logger.h:47:9: note: in instantiation of function template specialization 'raft::ctx_log::log<const char *, int, raft::consensus::vote_state &, raft::vnode &, detail::base_named_type<long, model::model_raft_term_id_type, std::integral_constant<bool, true>> &>' requested here
        log(ss::log_level::debug, format, std::forward<Args>(args)...);
        ^
/home/kefu/dev/redpanda/src/v/raft/consensus.cc:2493:19: note: in instantiation of function template specialization 'raft::ctx_log::debug<const char *, int, raft::consensus::vote_state &, raft::vnode &, detail::base_named_type<long, model::model_raft_term_id_type, std::integral_constant<bool, true>> &>' requested here
          _ctxlog.debug,
                  ^
1 error generated.

Signed-off-by: Kefu Chai <tchaikov@gmail.com>
(cherry picked from commit e9997aac45d12ab5881988f44f70da53eb8bd586)