cluster: specialize fmt::format() for feature_state::state
otherwise {fmt} v8 would cause FTBFS like:

ccache /usr/bin/clang++-15 -DBOOST_ASIO_HAS_STD_INVOKE_RESULT -DFMT_LOCALE -DFMT_SHARED -DSEASTAR_API_LEVEL=6 -DSEASTAR_DEBUG -DSEASTAR_DEBUG_SHARED_PTR -DSEASTAR_DEFAULT_ALLOCATOR -DSEASTAR_SCHEDULING_GROUPS_COUNT=16 -DSEASTAR_SHUFFLE_TASK_QUEUE -DSEASTAR_TYPE_ERASE_MORE -DXXH_PRIVATE_API -DZSTD_STATIC_LINKING_ONLY -I/home/kefu/dev/redpanda/src/v -I/home/kefu/dev/redpanda/build/src/v -isystem /home/kefu/dev/redpanda/build/deps_install/include -isystem /home/kefu/dev/redpanda/build/deps_install/include/hdr -fPIC -fsanitize=undefined -fsanitize=address -fcolor-diagnostics -g -fPIC -Wall -Wextra -Werror -Wno-missing-field-initializers -std=c++20 -U_FORTIFY_SOURCE -DSEASTAR_SSTRING -Werror=unused-result "-Wno-error=#warnings" -fstack-clash-protection -fsanitize=address -fsanitize=undefined -fno-sanitize=vptr -std=c++20 -MD -MT src/v/cluster/CMakeFiles/v_cluster.dir/feature_table.cc.o -MF src/v/cluster/CMakeFiles/v_cluster.dir/feature_table.cc.o.d -o src/v/cluster/CMakeFiles/v_cluster.dir/feature_table.cc.o -c /home/kefu/dev/redpanda/src/v/cluster/feature_table.cc
In file included from /home/kefu/dev/redpanda/src/v/cluster/feature_table.cc:12:
In file included from /home/kefu/dev/redpanda/src/v/cluster/feature_table.h:14:
In file included from /home/kefu/dev/redpanda/src/v/cluster/types.h:16:
In file included from /home/kefu/dev/redpanda/src/v/kafka/types.h:13:
In file included from /home/kefu/dev/redpanda/src/v/bytes/bytes.h:14:
In file included from /home/kefu/dev/redpanda/src/v/bytes/iobuf.h:14:
In file included from /home/kefu/dev/redpanda/src/v/bytes/details/io_byte_iterator.h:14:
In file included from /home/kefu/dev/redpanda/src/v/bytes/details/io_fragment.h:14:
In file included from /home/kefu/dev/redpanda/src/v/bytes/details/out_of_range.h:15:
In file included from /usr/include/fmt/format.h:48:
/usr/include/fmt/core.h:1727:3: error: static_assert failed due to requirement 'formattable' "Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt"
  static_assert(
  ^
/usr/include/fmt/core.h:1853:23: note: in instantiation of function template specialization 'fmt::detail::make_arg<true, fmt::basic_format_context<fmt::appender, char>, fmt::detail::type::custom_type, cluster::feature_state::state &, 0>' requested here
        data_{detail::make_arg<
                      ^
/usr/include/fmt/core.h:1872:10: note: in instantiation of function template specialization 'fmt::format_arg_store<fmt::basic_format_context<fmt::appender, char>, const char *, int, cluster::feature_update_action, cluster::feature_state::state>::format_arg_store<const char *&, int &, const cluster::feature_update_action &, cluster::feature_state::state &>' requested here
  return {std::forward<Args>(args)...};
         ^
/usr/include/fmt/core.h:3148:36: note: in instantiation of function template specialization 'fmt::make_format_args<fmt::basic_format_context<fmt::appender, char>, const char *&, int &, const cluster::feature_update_action &, cluster::feature_state::state &>' requested here
  return vformat_to(out, fmt, fmt::make_format_args(args...));
                                   ^
/home/kefu/dev/redpanda/build/deps_install/include/seastar/util/log.hh:208:33: note: in instantiation of function template specialization 'fmt::format_to<seastar::internal::log_buf::inserter_iterator, const char *, int, const cluster::feature_update_action &, cluster::feature_state::state, 0>' requested here
                    return fmt::format_to(it, fmt::runtime(fmt.format), std::forward<Args>(args)...);
                                ^
/home/kefu/dev/redpanda/build/deps_install/include/seastar/util/log.hh:321:9: note: in instantiation of function template specialization 'seastar::logger::log<const char *, int, const cluster::feature_update_action &, cluster::feature_state::state>' requested here
        log(log_level::warn, std::move(fmt), std::forward<Args>(args)...);
        ^
/home/kefu/dev/redpanda/src/v/cluster/feature_table.cc:156:26: note: in instantiation of function template specialization 'seastar::logger::warn<const char *, int, const cluster::feature_update_action &, cluster::feature_state::state>' requested here
              clusterlog.warn,
                         ^

Signed-off-by: Kefu Chai <tchaikov@gmail.com>
(cherry picked from commit 547150c108e7d27ff3758386320b7adaa70a9555)