schema_registry/protobuf: define *::error() later
so that the compiler understand we have a specialization for
fmt::formatter<err> when compiling io_error_collector::error()
and dp_error_collector::error() which in turn require
fmt::formatter<err> for printing io_error_collector::err using fmt.

otherwise we'd have following FTBFS:

FAILED: src/v/pandaproxy/schema_registry/CMakeFiles/v_pandaproxy_schema_registry.dir/protobuf.cc.o
ccache /usr/bin/clang++-15 -DBOOST_ASIO_HAS_STD_INVOKE_RESULT -DFMT_LOCALE -DFMT_SHARED -DSEASTAR_API_LEVEL=6 -DSEASTAR_DEBUG -DSEASTAR_DEBUG_SHARED_PTR -DSEASTAR_DEFAULT_ALLOCATOR -DSEAS
TAR_SCHEDULING_GROUPS_COUNT=16 -DSEASTAR_SHUFFLE_TASK_QUEUE -DSEASTAR_TYPE_ERASE_MORE -DXXH_PRIVATE_API -DZSTD_STATIC_LINKING_ONLY -I/home/kefu/dev/redpanda/src/v -I/home/kefu/dev/redpand
a/build/src/v -isystem /home/kefu/dev/redpanda/build/deps_install/include -isystem /home/kefu/dev/redpanda/build/deps_install/include/hdr -fPIC -fsanitize=undefined -fsanitize=address -fc
olor-diagnostics -g -fPIC -Wall -Wextra -Werror -Wno-missing-field-initializers -std=c++20 -U_FORTIFY_SOURCE -DSEASTAR_SSTRING -Werror=unused-result "-Wno-error=#warnings" -fstack-clash-p
rotection -fsanitize=address -fsanitize=undefined -fno-sanitize=vptr -std=c++20 -MD -MT src/v/pandaproxy/schema_registry/CMakeFiles/v_pandaproxy_schema_registry.dir/protobuf.cc.o -MF src/
v/pandaproxy/schema_registry/CMakeFiles/v_pandaproxy_schema_registry.dir/protobuf.cc.o.d -o src/v/pandaproxy/schema_registry/CMakeFiles/v_pandaproxy_schema_registry.dir/protobuf.cc.o -c /
home/kefu/dev/redpanda/src/v/pandaproxy/schema_registry/protobuf.cc
In file included from /home/kefu/dev/redpanda/src/v/pandaproxy/schema_registry/protobuf.cc:12:
In file included from /home/kefu/dev/redpanda/src/v/pandaproxy/schema_registry/protobuf.h:15:
In file included from /home/kefu/dev/redpanda/src/v/pandaproxy/schema_registry/types.h:15:
In file included from /home/kefu/dev/redpanda/src/v/model/metadata.h:14:
In file included from /home/kefu/dev/redpanda/src/v/model/fundamental.h:15:
In file included from /home/kefu/dev/redpanda/src/v/ssx/sformat.h:16:
In file included from /home/kefu/dev/redpanda/build/deps_install/include/fmt/format.h:48:
/home/kefu/dev/redpanda/build/deps_install/include/fmt/core.h:2672:12: error: call to deleted constructor of 'conditional_t<has_formatter<mapped_type, context>::value, formatter<mapped_ty
pe, char_type>, fallback_formatter<fmt::join_view<__gnu_cxx::__normal_iterator<const pandaproxy::schema_registry::io_error_collector::err *, std::vector<pandaproxy::schema_registry::io_er
ror_collector::err>>, __gnu_cxx::__normal_iterator<const pandaproxy::schema_registry::io_error_collector::err *, std::vector<pandaproxy::schema_registry::io_error_collector::err>>>, char_
type>>' (aka 'fmt::detail::fallback_formatter<fmt::join_view<__gnu_cxx::__normal_iterator<const pandaproxy::schema_registry::io_error_collector::err *, std::vector<pandaproxy::schema_regi
stry::io_error_collector::err>>, __gnu_cxx::__normal_iterator<const pandaproxy::schema_registry::io_error_collector::err *, std::vector<pandaproxy::schema_registry::io_error_collector::er
r>>>>')
  auto f = conditional_t<has_formatter<mapped_type, context>::value,
           ^
/home/kefu/dev/redpanda/build/deps_install/include/fmt/core.h:2906:23: note: in instantiation of function template specialization 'fmt::detail::parse_format_specs<fmt::join_view<__gnu_cxx
::__normal_iterator<const pandaproxy::schema_registry::io_error_collector::err *, std::vector<pandaproxy::schema_registry::io_error_collector::err>>, __gnu_cxx::__normal_iterator<const pa
ndaproxy::schema_registry::io_error_collector::err *, std::vector<pandaproxy::schema_registry::io_error_collector::err>>>, fmt::detail::compile_parse_context<char>>' requested here
        parse_funcs_{&parse_format_specs<Args, parse_context_type>...} {}
                      ^
/home/kefu/dev/redpanda/build/deps_install/include/fmt/core.h:3068:47: note: in instantiation of member function 'fmt::detail::format_string_checker<char, fmt::detail::error_handler, fmt:
:join_view<__gnu_cxx::__normal_iterator<const pandaproxy::schema_registry::io_error_collector::err *, std::vector<pandaproxy::schema_registry::io_error_collector::err>>, __gnu_cxx::__norm
al_iterator<const pandaproxy::schema_registry::io_error_collector::err *, std::vector<pandaproxy::schema_registry::io_error_collector::err>>>>::format_string_checker' requested here
      detail::parse_format_string<true>(str_, checker(s, {}));
                                              ^
/home/kefu/dev/redpanda/src/v/pandaproxy/schema_registry/protobuf.cc:56:23: note: in instantiation of function template specialization 'fmt::basic_format_string<char, fmt::join_view<__gnu
_cxx::__normal_iterator<const pandaproxy::schema_registry::io_error_collector::err *, std::vector<pandaproxy::schema_registry::io_error_collector::err>>, __gnu_cxx::__normal_iterator<cons
t pandaproxy::schema_registry::io_error_collector::err *, std::vector<pandaproxy::schema_registry::io_error_collector::err>>>>::basic_format_string<char[3], 0>' requested here
          fmt::format("{}", fmt::join(_errors, "; "))};
                      ^
/home/kefu/dev/redpanda/build/deps_install/include/fmt/core.h:1041:3: note: 'fallback_formatter' has been explicitly marked deleted here
  fallback_formatter() = delete;
  ^

Signed-off-by: Kefu Chai <tchaikov@gmail.com>
(cherry picked from commit 235272743b3ea5041f19655fe15883e7c802cbae)