cl/tests: ClusterLinkingProgressVerifier fix
There are a class of failures that result in errors such as:
```
ducktape.errors.TimeoutError: Timed out waiting for status endpoint KgoVerifierConsumerGroupConsumer-0-140503148073056 to be available
```

This is due to:
```
time="2025-11-07T15:15:05Z" level=info msg="Reading with consumer group source-cg-source-topic"
time="2025-11-07T15:15:05Z" level=error msg="More partitions in valid_offsets file than in topic!"
```

And the reason for that is that the consumer is running on a different
node than the producer.

The fix is in two parts:
* Wait for the file before creating the consumer
* Run the consumer on the same node as the producer

Signed-off-by: Ben Pope <ben@redpanda.com>