v: differentiate compile-time fmt str from runtime str
as fmt v8 started to error if we pass non-constexpr fmt str to
fmt::format() and friends, like:

/home/kefu/dev/redpanda/src/v/bytes/details/out_of_range.h:20:41: error: call to consteval function 'fmt::basic_format_string<char, unsigned long &, unsigned long &>::basic_format_string<
const char *, 0>' is not a constant expression
    throw std::out_of_range(fmt::format(fmt, A, B));
                                        ^
/usr/include/fmt/core.h:3057:67: note: function parameter 'fmt' with unknown value cannot be used in a constant expression
  FMT_CONSTEVAL FMT_INLINE basic_format_string(const S& s) : str_(s) {
                                                                  ^
/home/kefu/dev/redpanda/src/v/bytes/details/out_of_range.h:20:41: note: in call to 'basic_format_string(fmt)'
    throw std::out_of_range(fmt::format(fmt, A, B));
                                        ^
/home/kefu/dev/redpanda/src/v/bytes/details/out_of_range.h:19:32: note: declared here
throw_out_of_range(const char* fmt, size_t A, size_t B) {

so need to differentiate the compile-time str from those which can
be specified at runtime.

Signed-off-by: Kefu Chai <tchaikov@gmail.com>
(cherry picked from commit 03cc2bcef5e5220dfadf1a0c55ec05113c89ec62)