storage: specialize fmt::formtter() for recovert_state
to address the FTBFS like

ccache /usr/bin/clang++-15 -DFMT_LOCALE -DFMT_SHARED -DSEASTAR_API_LEVEL=6 -DSEASTAR_DEBUG -DSEASTAR_DEBUG_SHARED_PTR -DSEASTAR_DEFAULT_ALLOCATOR -DSEASTAR_SCHEDULING_GROUPS_COUNT=16 -DSE
ASTAR_SHUFFLE_TASK_QUEUE -DSEASTAR_TYPE_ERASE_MORE -DXXH_PRIVATE_API -DZSTD_STATIC_LINKING_ONLY -I/home/kefu/dev/redpanda/src/v -I/home/kefu/dev/redpanda/build/src/v -isystem /home/kefu/d
ev/redpanda/build/deps_install/include -isystem /home/kefu/dev/redpanda/build/deps_install/include/hdr -fPIC -fsanitize=undefined -fsanitize=address -fcolor-diagnostics -g -fPIC -Wall -We
xtra -Werror -Wno-missing-field-initializers -std=c++20 -U_FORTIFY_SOURCE -DSEASTAR_SSTRING -Werror=unused-result "-Wno-error=#warnings" -fstack-clash-protection -fsanitize=address -fsani
tize=undefined -fno-sanitize=vptr -std=c++20 -MD -MT src/v/storage/CMakeFiles/v_storage.dir/segment_utils.cc.o -MF src/v/storage/CMakeFiles/v_storage.dir/segment_utils.cc.o.d -o src/v/sto
rage/CMakeFiles/v_storage.dir/segment_utils.cc.o -c /home/kefu/dev/redpanda/src/v/storage/segment_utils.cc
In file included from /home/kefu/dev/redpanda/src/v/storage/segment_utils.cc:10:
In file included from /home/kefu/dev/redpanda/src/v/storage/segment_utils.h:13:
In file included from /home/kefu/dev/redpanda/src/v/model/record_batch_reader.h:15:
In file included from /home/kefu/dev/redpanda/src/v/model/record.h:14:
In file included from /home/kefu/dev/redpanda/src/v/bytes/iobuf.h:14:
In file included from /home/kefu/dev/redpanda/src/v/bytes/details/io_byte_iterator.h:14:
In file included from /home/kefu/dev/redpanda/src/v/bytes/details/io_fragment.h:14:
In file included from /home/kefu/dev/redpanda/src/v/bytes/details/out_of_range.h:15:
In file included from /usr/include/fmt/format.h:48:
/usr/include/fmt/core.h:1727:3: error: static_assert failed due to requirement 'formattable' "Cannot format an argument. To make type T formattable provide a formatter<T> specialization:
https://fmt.dev/latest/api.html#udt"
  static_assert(
  ^
/usr/include/fmt/core.h:1853:23: note: in instantiation of function template specialization 'fmt::detail::make_arg<true, fmt::basic_format_context<fmt::appender, char>, fmt::detail::type:
:custom_type, storage::compacted_index::recovery_state &, 0>' requested here
        data_{detail::make_arg<
                      ^
/usr/include/fmt/core.h:1872:10: note: in instantiation of function template specialization 'fmt::format_arg_store<fmt::basic_format_context<fmt::appender, char>, const char *, int, std::
filesystem::path, storage::compacted_index::recovery_state>::format_arg_store<const char *&, int &, std::filesystem::path &, storage::compacted_index::recovery_state &>' requested here
  return {std::forward<Args>(args)...};
         ^
/usr/include/fmt/core.h:3148:36: note: in instantiation of function template specialization 'fmt::make_format_args<fmt::basic_format_context<fmt::appender, char>, const char *&, int &, st
d::filesystem::path &, storage::compacted_index::recovery_state &>' requested here
  return vformat_to(out, fmt, fmt::make_format_args(args...));
                                   ^
/home/kefu/dev/redpanda/build/deps_install/include/seastar/util/log.hh:208:33: note: in instantiation of function template specialization 'fmt::format_to<seastar::internal::log_buf::inser
ter_iterator, const char *, int, std::filesystem::path &, storage::compacted_index::recovery_state &, 0>' requested here
                    return fmt::format_to(it, fmt::runtime(fmt.format), std::forward<Args>(args)...);
                                ^
/home/kefu/dev/redpanda/build/deps_install/include/seastar/util/log.hh:367:9: note: in instantiation of function template specialization 'seastar::logger::log<const char *, int, std::file
system::path &, storage::compacted_index::recovery_state &>' requested here
        log(log_level::trace, std::move(fmt), std::forward<Args>(args)...);
        ^
/home/kefu/dev/redpanda/src/v/storage/segment_utils.cc:540:22: note: in instantiation of function template specialization 'seastar::logger::trace<const char *, int, std::filesystem::path
&, storage::compacted_index::recovery_state &>' requested here
          vlog(gclog.trace, "segment {} compaction state: {}", idx_path, state);
                     ^

Signed-off-by: Kefu Chai <tchaikov@gmail.com>
(cherry picked from commit 98a1df7966ce9bfc7679e922a791df49aad67035)