rpc: include ssx/sformat.h early
to get the fmt::formatter<seastar::sstring> instantiated before
it is implicit instantiated by Seastar library.

this change helps to address the FTBFS of

/usr/bin/clang++-15 -DFMT_LOCALE -DFMT_SHARED -DSEASTAR_API_LEVEL=6 -DSEASTAR_DEBUG -DSEASTAR_DEBUG_SHARED_PTR -DSEASTAR_DEFAULT_ALLOCATOR -DSEASTAR_SCHEDULING_GROUPS_COUNT=16 -DSEASTAR_SHUFFLE_TASK_QUEUE -DSEASTAR_TYPE_ERASE_MORE -DXXH_PRIVATE_API -DZSTD_STATIC_LINKING_ONLY -I/home/kefu/dev/redpanda/src/v -I/home/kefu/dev/redpanda/build/src/v -isystem /home/kefu/dev/redpanda/build/deps_install/include -isystem /home/kefu/dev/redpanda/build/deps_install/include/hdr -fPIC -fsanitize=undefined -fsanitize=address -fcolor-diagnostics -g -fPIC -Wall -Wextra -Werror -Wno-missing-field-initializers -std=c++20 -U_FORTIFY_SOURCE -DSEASTAR_SSTRING -Werror=unused-result "-Wno-error=#warnings" -fstack-clash-protection -fsanitize=address -fsanitize=undefined -fno-sanitize=vptr -std=c++20 -MD -MT src/v/rpc/CMakeFiles/v_rpc.dir/reconnect_transport.cc.o -MF src/v/rpc/CMakeFiles/v_rpc.dir/reconnect_transport.cc.o.d -o src/v/rpc/CMakeFiles/v_rpc.dir/reconnect_transport.cc.o -c /home/kefu/dev/redpanda/src/v/rpc/reconnect_transport.cc
In file included from /home/kefu/dev/redpanda/src/v/rpc/reconnect_transport.cc:13:
In file included from /home/kefu/dev/redpanda/src/v/raft/logger.h:14:
In file included from /home/kefu/dev/redpanda/src/v/model/fundamental.h:15:
/home/kefu/dev/redpanda/src/v/ssx/sformat.h:19:13: error: explicit specialization of 'fmt::formatter<seastar::basic_sstring<char, unsigned int, 15, true>>' after instantiation
struct fmt::formatter<seastar::sstring> {
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/type_traits:971:30: note: implicit instantiation first required here
    : public __bool_constant<__is_constructible(_Tp, _Args...)>
                             ^

Signed-off-by: Kefu Chai <tchaikov@gmail.com>
(cherry picked from commit 9984a278e6a057239d6d58cb437971a46d26b908)