schema_registry: Split project_ids
A common use of `POST /subjects/{subject}/versions` is to get the
schema ID of an existing subject-version.

This case can be optimised by not taking the write_sem unless a new
schema or version needs to be written to the topic.

Split out `get_schema_version` from `project_ids` to facilitate that.

NOTE:
I haven't got this correct, there's a failing test:

```
INFO  2023-10-09 18:26:47,650 [shard  0:main] pandaproxy_test_fixture::schema_registry_post_subjects_subject_version_with_version_no_compat - Post schema as v2 (higher than next_version)
/home/ben/development/src/github.com/BenPope/redpanda-clang-16/src/v/pandaproxy/schema_registry/test/post_subjects_subject_version.cc(259): fatal error: in "schema_registry_post_subjects_subject_version_with_version_no_compat": critical check versions == expected has failed [{{1}} != {{2}}]
```

Signed-off-by: Ben Pope <ben@redpanda.com>