k/fetch: specialize fmt::format() for isolation
so it can be printed using fmt::format()

otherwise we'd have following build failure when compiling with {fmt}
v8:

ccache /usr/bin/clang++-15 -DBOOST_ASIO_HAS_STD_INVOKE_RESULT -DFMT_LOCALE -DFMT_SHARED -DSEASTAR_API_LEVEL=6 -DSEASTAR_DEBUG -DSEASTAR_DEBUG_SHARED_PTR -DSEASTAR_DEFAULT_ALLOCATOR -DSEASTAR_SCHEDULING_GROUPS_COUNT=16 -DSEASTAR_SHUFFLE_TASK_QUEUE -DSEASTAR_TYPE_ERASE_MORE -DXXH_PRIVATE_API -DZSTD_STATIC_LINKING_ONLY -I/home/kefu/dev/redpanda/src/v -I/home/kefu/dev/redpanda/build/src/v -isystem /home/kefu/dev/redpanda/build/deps_install/include -isystem /home/kefu/dev/redpanda/build/deps_install/include/hdr -fPIC -fsanitize=undefined -fsanitize=address -fcolor-diagnostics -g -fPIC -Wall -Wextra -Werror -Wno-missing-field-initializers -std=c++20 -U_FORTIFY_SOURCE -DSEASTAR_SSTRING -Werror=unused-result "-Wno-error=#warnings" -fstack-clash-protection -fsanitize=address -fsanitize=undefined -fno-sanitize=vptr -std=c++20 -MD -MT src/v/kafka/CMakeFiles/v_kafka.dir/server/handlers/api_versions.cc.o -MF src/v/kafka/CMakeFiles/v_kafka.dir/server/handlers/api_versions.cc.o.d -o src/v/kafka/CMakeFiles/v_kafka.dir/server/handlers/api_versions.cc.o -c /home/kefu/dev/redpanda/src/v/kafka/server/handlers/api_versions.cc
In file included from /home/kefu/dev/redpanda/src/v/kafka/server/handlers/api_versions.cc:10:
In file included from /home/kefu/dev/redpanda/src/v/kafka/protocol/response_writer.h:14:
In file included from /home/kefu/dev/redpanda/src/v/bytes/bytes.h:14:
In file included from /home/kefu/dev/redpanda/src/v/bytes/iobuf.h:14:
In file included from /home/kefu/dev/redpanda/src/v/bytes/details/io_byte_iterator.h:14:
In file included from /home/kefu/dev/redpanda/src/v/bytes/details/io_fragment.h:14:
In file included from /home/kefu/dev/redpanda/src/v/bytes/details/out_of_range.h:15:
In file included from /usr/include/fmt/format.h:48:
/usr/include/fmt/core.h:1727:3: error: static_assert failed due to requirement 'formattable' "Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt"
  static_assert(
  ^
/usr/include/fmt/core.h:1853:23: note: in instantiation of function template specialization 'fmt::detail::make_arg<true, fmt::basic_format_context<fmt::appender, char>, fmt::detail::type::custom_type, const model::isolation_level &, 0>' requested here
        data_{detail::make_arg<
                      ^
/usr/include/fmt/format.h:844:10: note: in instantiation of function template specialization 'fmt::format_arg_store<fmt::basic_format_context<fmt::appender, char>, const detail::base_named_type<long, model::model_offset_type, std::integral_constant<bool, true>>, const detail::base_named_type<long, model::model_offset_type, std::integral_constant<bool, true>>, const model::isolation_level, const unsigned long, const bool, const detail::base_named_type<int, kafka::leader_epoch_tag, std::integral_constant<bool, true>>>::format_arg_store<const detail::base_named_type<long, model::model_offset_type, std::integral_constant<bool, true>> &, const detail::base_named_type<long, model::model_offset_type, std::integral_constant<bool, true>> &, const model::isolation_level &, const unsigned long &, const bool &, const detail::base_named_type<int, kafka::leader_epoch_tag, std::integral_constant<bool, true>> &>' requested here
  return {args...};
         ^
/usr/include/fmt/ostream.h:131:15: note: in instantiation of function template specialization 'fmt::make_args_checked<const detail::base_named_type<long, model::model_offset_type, std::integral_constant<bool, true>> &, const detail::base_named_type<long, model::model_offset_type, std::integral_constant<bool, true>> &, const model::isolation_level &, const unsigned long &, const bool &, const detail::base_named_type<int, kafka::leader_epoch_tag, std::integral_constant<bool, true>> &, char[131], char>' requested here
         fmt::make_args_checked<Args...>(format_str, args...));
              ^
/home/kefu/dev/redpanda/src/v/kafka/server/handlers/fetch.h:153:14: note: in instantiation of function template specialization 'fmt::print<char[131], const detail::base_named_type<long, model::model_offset_type, std::integral_constant<bool, true>> &, const detail::base_named_type<long, model::model_offset_type, std::integral_constant<bool, true>> &, const model::isolation_level &, const unsigned long &, const bool &, const detail::base_named_type<int, kafka::leader_epoch_tag, std::integral_constant<bool, true>> &, char>' requested here
        fmt::print(
             ^

Signed-off-by: Kefu Chai <tchaikov@gmail.com>
(cherry picked from commit c68f46a8dd3c887e4fa3ef625fae47a868f68185)