ssx/format: add a wrapper for fmt::format_to()
since fmt v8, fmt::format_to() has been deprecated in favor the one
which accepts an appender or a back_inserter. so add a wrapper to
silence this warning.

for the reference, the warning looks like:

/home/kefu/dev/redpanda/src/v/utils/retry_chain_node.cc:245:18: error: 'format_to<unsigned short &, 500UL, std::allocator<char>>' is deprecated [-Werror,-Wdeprecated-declarations]
            fmt::format_to(str, "fiber{}", *id);
                 ^
/usr/include/fmt/format.h:3064:1: note: 'format_to<unsigned short &, 500UL, std::allocator<char>>' has been explicitly marked deprecated here
FMT_DEPRECATED auto format_to(basic_memory_buffer<char, SIZE, Allocator>& buf,
^
/usr/include/fmt/core.h:224:30: note: expanded from macro 'FMT_DEPRECATED'                                                                                                                 #    define FMT_DEPRECATED [[deprecated]]
                             ^

Signed-off-by: Kefu Chai <tchaikov@gmail.com>
(cherry picked from commit 19897390efea6b99a4e066bcac356a15eb2c5b66)